# Generated by Django 3.1 on 2020-08-25 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['expense_date'],
            },
        ),
    ]
