# Generated by Django 3.1.1 on 2020-09-16 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=255, verbose_name='Name of the expense')),
                ('expense_invoice_date', models.DateField(verbose_name='Date invoice for the expense was generated')),
                ('expense_paid_date', models.DateField(blank=True, verbose_name='Date expense was paid')),
                ('expense_paid', models.BooleanField(default=False, verbose_name='If expense is paid or not')),
                ('expense_reason', models.CharField(max_length=255, verbose_name='Description about the expense')),
                ('is_reccuring', models.BooleanField(default=False, verbose_name='Is expense reccuring every week, month or year')),
                ('recurrsion_duration', models.CharField(choices=[('SW', 'Weekly'), ('BW', 'Bi-Weekly'), ('M', 'Monthly'), ('Y', 'Yearly'), ('S', 'Single Time')], max_length=2, verbose_name='Reccuring Frequency')),
                ('expense_amount', models.IntegerField(verbose_name='Totals Amount of the expense')),
                ('expense_generated_currency', models.CharField(choices=[('USD', 'United States Dollars'), ('CAD', 'Canadian Dollars')], max_length=3, verbose_name='Currency in whicih expense was generated')),
                ('expense_paid_currency', models.CharField(choices=[('USD', 'United States Dollars'), ('CAD', 'Canadian Dollars')], max_length=3, verbose_name='Currency in which expense was paid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Name of the user who enters the data')),
            ],
        ),
    ]
