# Generated by Django 3.0.6 on 2020-06-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20200610_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='docuemnt_type',
            field=models.CharField(max_length=256),
        ),
    ]
