# Generated by Django 3.0.6 on 2020-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.IntegerField()),
                ('origin_city', models.CharField(max_length=20)),
                ('destination_city', models.CharField(max_length=20)),
            ],
        ),
    ]
