# Generated by Django 3.0.6 on 2020-05-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_description_2',
            field=models.CharField(default='Add a Description', max_length=256),
        ),
    ]
