# Generated by Django 3.0.6 on 2020-05-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_expense_expense_description_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_description_2',
            field=models.CharField(max_length=256),
        ),
    ]
