# Generated by Django 3.0.6 on 2020-06-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_account_type', models.CharField(max_length=100)),
                ('expense_transaction_date', models.DateField()),
                ('expense_name', models.CharField(max_length=100)),
                ('expense_description_1', models.CharField(default='No Descriptiong Available', max_length=256)),
                ('expense_description_2', models.CharField(default='No Descriptiong Available', max_length=256)),
                ('expense_amount_cad', models.IntegerField(default=0)),
                ('expense_amount_usd', models.IntegerField(default=0)),
                ('expense_gst', models.IntegerField(default=0)),
                ('expense_pst', models.IntegerField(default=0)),
                ('expense_pvt', models.IntegerField(default=0)),
                ('expense_quarter', models.IntegerField(default=1)),
                ('expense_year', models.IntegerField(default=1000)),
                ('docuemnt_type', models.CharField(max_length=256)),
            ],
        ),
    ]
